title: Your awesome title
email: barsonymarcell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    An open source blog about cyber security with love.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://marcellbarsony.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marcellbarsony
github_username: marcellbarsony
linkedin_username: marcellbarsony
author: Marcell Barsony
plugins:
  - jekyll-feed
